### ISSUE TITLE
Menu component Icon alignment

### ISSUE THREAD

**Issue by mozkarakoc** [KuveytTurk/boa#97]
**Describe the bug**
When the menu component was used with an icon, the icon sticks to menu text.

**To Reproduce**
```jsx
<Menu
  context={context}
  disabled={false}
  iconType="horizontal"
  items={[
    {
      leftIcon: {
        dynamicIcon: 'Home',
        iconProperties: {
          style: {
            color: '#757575',
            height: 20,
            margin: 'auto 0px auto 24px',
            right: 0,
            top: '50%',
            width: 20
          }
        }
      },
      text: 'Istanbul',
      value: '34'
    },
    {
      text: 'Ankara',
      value: '06'
    }
  ]}
  multiple={false}
  primaryTextPadding="0px 24px 0px 24px"
  visible
/>
```

**Expected behavior**
From the guideline
![image](https://user-images.githubusercontent.com/41525700/53784324-f481d500-3f25-11e9-99a6-9d17b49914e6.png)

**Screenshots**
From the storybook (theme was not selected)
![image](https://user-images.githubusercontent.com/41525700/53784336-fe0b3d00-3f25-11e9-8729-275654ad5aee.png)

**Environment:**
 - Browser: Chrome
 - Package Versions: v0.1.4

**Comment by canpolatoral** [comment]
#99 #

**Comment by canpolatoral** [comment]
#99 fixed.
